### ISSUE TITLE
the checkpoint 16k segformer

### ISSUE THREAD

**Issue by aivyon** [EckoTan0804/flying-guide-dog#1]
Hi
Thank you for sharing your work.
Can you please share the  checkpoint = "weights/segmentation/iter_160000.pth"
mentioneed in seg_models.py
IT would be very much appreciated.
Thank you a lot!!

**Comment by EckoTan0804** [comment]
> Hi Thank you for sharing your work. Can you please share the checkpoint = "weights/segmentation/iter_160000.pth" mentioneed in seg_models.py IT would be very much appreciated. Thank you a lot!!

Hi. Thanks for your interest!
I have uploaded the checkpoint to [Google Drive](https://drive.google.com/drive/folders/1efvfGxh2f1nCppO9YaPn6SyUQjG--QkC?usp=sharing). However, I have renamed it to `SegFormer_b0_Mapillary.pth`. Therefore, it may be incompatible with the code in `seg_models.py`. I will fix this bug ASAP.

**Comment by aivyon** [comment]
Thank you!!

**Comment by aivyon** [comment]
Hi. Thank you for sharing your work. 
Did you have a chance looking into the matter of the checkpoint being compatible with the code in seg_models.py as per your last response.
Thank you!
